sudo: required

services:
  - docker


language: go
go:
  - "1.12"

install: skip

jobs:
  include:
    - stage: test
      env: GO111MODULE=on
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
        - export PATH=$PATH:$(go env GOPATH)/bin
        - golangci-lint --version
      script: ./scripts/runLint.sh

    - script: ./scripts/runUnitTests.sh
      env: GO111MODULE=on

    - script: ./scripts/runIntegrationAcceptance.sh
      env: GO111MODULE=on

    - script: ./scripts/runIntegrationPerformance.sh
      env: GO111MODULE=on

    - script: ./scripts/runIntegrationFaultInjection.sh
      env: GO111MODULE=on

    - script: ./scripts/runIntegrationMeteor.sh
      env: GO111MODULE=on
