version: "3"
services:
  test:
    build: .
    depends_on:
      - oplogtoredis
      - mongo
      - redis
    command:
      - /wait-for.sh
      - --timeout=60
      - mongo:27017
      - '--'
      - /wait-for.sh
      - --timeout=60
      - redis:6379
      - '--'
      - /go/src/github.com/tulip/oplogtoredis/integration-tests/performance/entry.sh
    environment:
      - MONGO_URL=mongodb://mongo/tests
      - REDIS_URL=redis://redis
    volumes:
      - ../../scripts/wait-for.sh:/wait-for.sh
      - ../..:/go/src/github.com/tulip/oplogtoredis
  oplogtoredis:
    build: ../..
    environment:
      - OTR_MONGO_URL=mongodb://mongo/tests
      - OTR_REDIS_URL=redis://redis
    depends_on:
      - mongo
      - redis
    volumes:
      - ../../scripts/wait-for.sh:/wait-for.sh
    command:
      - /wait-for.sh
      - --timeout=60
      - mongo:27017
      - '--'
      - /wait-for.sh
      - --timeout=60
      - redis:6379
      - '--'
      - /bin/oplogtoredis
  mongo:
    image: mongo:3.2.19
    command: "mongod --replSet myapp --port 27017"
    logging:
      driver: none
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:3.2.4
    logging:
      driver: none

volumes:
  mongo_data:
